name: Generate Javadoc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Javadoc
      run: mvn clean javadoc:javadoc

    - name: List files in target/site directory
      run: ls -R target/site  # Debug step to verify if apidocs is generated

    - name: Upload Javadoc as artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: javadoc
        path: target/site/apidocs  # Ensure this path is correct
